# Site settings
title: Parker Hu Blog
SEOTitle: 古月胡的博客 | Parker Hu Blog
header-img: img/post-bg-desk.jpg
email: hu2990414272@gmail.com
description: "I want to go back to Langlang Mountain."
keyword: "Parker Hu, PH, 古月胡的博客, huhuizhong, raspberry pi, RK, reCamera"
url: "https://litxaohu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/litxaohu/litxaohu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Embedded application engineer, learning AI cameras!"
sidebar-avatar: /img/Logo-150x150.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     litxaohu
#zhihu_username:     litxaohu
github_username:    litxaohu
#facebook_username:  litxaohu
#jianshu_username:   e71990ada2fd
#twitter_username:   litxaohu




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Ov23li3VYT2jonisPA2j                            #生成的clientID
  clientSecret: d5fc48b75db88c2760801d42b16066f45d2c0d16    #生成的clientSecret
  repo: litxaohu.github.io    #仓库名称
  owner: litxaohu    #github用户名
  admin: litxaohu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: aae04e360ad7363865b403ad0300ec4c

# Google Analytics
ga_track_id: 'G-LSN3P23W37'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "博客园·hbzjkhhz",
        href: "https://www.cnblogs.com/hbzjkhhz/articles/17606852.html"
    },{
        title: "飞书",
        href: "https://ucncjjg0ue3c.feishu.cn/drive/home/"
    },{
        title: "Bilbil",
        href: "https://www.bilibili.com/opus/851870754179907591"
    },{
        title: "CSDN",
        href: "https://blog.csdn.net/qq_57120137/article/details/150216570?spm=1001.2014.3001.5501"
    }
]
